services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_api_server
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8072 --reload"
    ports:
      - "8072:8072"
    volumes:
      - ./app:/code/app
      - ./shared_audio:/code/shared_audio
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_worker
    command: >
      celery -A app.worker.celery_app worker -l info 
      --pool=solo 
      --concurrency=1
      -Q gpu_tasks
    volumes:
      - ./app:/code/app
      - ./shared_audio:/code/shared_audio
      - /usr/local/cuda/lib64:/usr/local/cuda/lib64
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_flower
    command: >
      celery -A app.worker.celery_app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./app:/code/app
      - ./shared_audio:/code/shared_audio
    env_file: .env
    restart: unless-stopped
    depends_on:
      - worker
