# docker-compose.yml (Updated)

version: "3.8"

services:
  # -------------------------------------------------------------
  #  The 'redis' service has been REMOVED from this file.
  # -------------------------------------------------------------

  # -------------------------------------------------------------
  #  API Server: Handles HTTP and WebSocket connections
  # -------------------------------------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_api_server
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - shared_audio_files:/app/shared_audio
    env_file: .env
    # 'depends_on: - redis' has been REMOVED.
    restart: unless-stopped

  # -------------------------------------------------------------
  #  GPU Worker: Executes heavy AI tasks
  # -------------------------------------------------------------
  worker-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_gpu_worker
    command: >
      celery -A app.worker.celery_app worker -l info 
      --pool=solo 
      -Q gpu_tasks 
      --concurrency=1
    volumes:
      - ./app:/app
      - shared_audio_files:/app/shared_audio
    env_file: .env
    # 'depends_on: - api' and '- redis' have been REMOVED for simplicity.
    # The worker will automatically try to connect to Redis when it starts.
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # -------------------------------------------------------------
  #  CPU Worker
  # -------------------------------------------------------------
  worker-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_cpu_worker
    command: >
      celery -A app.worker.celery_app worker -l info 
      -Q cpu_tasks 
      --concurrency=4
    volumes:
      - ./app:/app
    env_file: .env
    # 'depends_on: - api' and '- redis' have been REMOVED.
    restart: unless-stopped

volumes:
  shared_audio_files:
    driver: local
